from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_input_widget(object):
    def setupUi(self, input_widget):
        input_widget.setObjectName("input_widget")
        input_widget.resize(700, 132)
        input_widget.setMinimumSize(QtCore.QSize(700, 0))
        self.gridLayout = QtWidgets.QGridLayout(input_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.work_type = QtWidgets.QComboBox(input_widget)
        self.work_type.setObjectName("work_type")
        self.gridLayout.addWidget(self.work_type, 1, 0, 1, 1)
        self.lesson = QtWidgets.QComboBox(input_widget)
        self.lesson.setEditable(False)
        self.lesson.setCurrentText("")
        self.lesson.setObjectName("lesson")
        self.gridLayout.addWidget(self.lesson, 0, 0, 1, 1)
        self.actual_layout = QtWidgets.QHBoxLayout()
        self.actual_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.actual_layout.setObjectName("actual_layout")
        self.actual_layout_2 = QtWidgets.QLabel(input_widget)
        self.actual_layout_2.setObjectName("actual_layout_2")
        self.actual_layout.addWidget(self.actual_layout_2)
        self.actual = QtWidgets.QDateEdit(input_widget)
        self.actual.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 9, 1), QtCore.QTime(0, 0, 0)))
        self.actual.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 9, 1), QtCore.QTime(0, 0, 0)))
        self.actual.setObjectName("actual")
        self.actual_layout.addWidget(self.actual)
        self.gridLayout.addLayout(self.actual_layout, 0, 2, 1, 1)
        self.deadline_layout = QtWidgets.QHBoxLayout()
        self.deadline_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.deadline_layout.setObjectName("deadline_layout")
        self.deadline_label = QtWidgets.QLabel(input_widget)
        self.deadline_label.setObjectName("deadline_label")
        self.deadline_layout.addWidget(self.deadline_label)
        self.deadline = QtWidgets.QDateEdit(input_widget)
        self.deadline.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 9, 1), QtCore.QTime(0, 0, 0)))
        self.deadline.setMinimumDate(QtCore.QDate(2017, 9, 1))
        self.deadline.setObjectName("deadline")
        self.deadline_layout.addWidget(self.deadline)
        self.gridLayout.addLayout(self.deadline_layout, 1, 2, 1, 1)
        self.priority_layout = QtWidgets.QHBoxLayout()
        self.priority_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.priority_layout.setObjectName("priority_layout")
        self.priority_label = QtWidgets.QLabel(input_widget)
        self.priority_label.setObjectName("priority_label")
        self.priority_layout.addWidget(self.priority_label)
        self.priority = QtWidgets.QDoubleSpinBox(input_widget)
        self.priority.setMaximumSize(QtCore.QSize(80, 16777215))
        self.priority.setObjectName("priority")
        self.priority_layout.addWidget(self.priority)
        self.gridLayout.addLayout(self.priority_layout, 1, 3, 1, 1)
        self.time_layout = QtWidgets.QHBoxLayout()
        self.time_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.time_layout.setObjectName("time_layout")
        self.time_label = QtWidgets.QLabel(input_widget)
        self.time_label.setObjectName("time_label")
        self.time_layout.addWidget(self.time_label)
        self.time = QtWidgets.QTimeEdit(input_widget)
        self.time.setMaximumSize(QtCore.QSize(80, 16777215))
        self.time.setObjectName("time")
        self.time_layout.addWidget(self.time)
        self.gridLayout.addLayout(self.time_layout, 0, 3, 1, 1)
        self.add_button = QtWidgets.QPushButton(input_widget)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 2, 3, 1, 1)

        self.retranslateUi(input_widget)
        QtCore.QMetaObject.connectSlotsByName(input_widget)
        input_widget.setTabOrder(self.lesson, self.work_type)
        input_widget.setTabOrder(self.work_type, self.actual)
        input_widget.setTabOrder(self.actual, self.deadline)
        input_widget.setTabOrder(self.deadline, self.time)
        input_widget.setTabOrder(self.time, self.priority)
        input_widget.setTabOrder(self.priority, self.add_button)

    def retranslateUi(self, input_widget):
        _translate = QtCore.QCoreApplication.translate
        input_widget.setWindowTitle(_translate("input_widget", "Form"))
        self.work_type.setToolTip(_translate("input_widget", "Тип работы"))
        self.lesson.setToolTip(_translate("input_widget", "Урок"))
        self.actual_layout_2.setText(_translate("input_widget", "Дата начала"))
        self.actual.setToolTip(_translate("input_widget", "Дата начала"))
        self.deadline_label.setText(_translate("input_widget", "Дата окончания"))
        self.deadline.setToolTip(_translate("input_widget", "Дата окончания"))
        self.priority_label.setText(_translate("input_widget", "Приоритет"))
        self.priority.setToolTip(_translate("input_widget", "Приоритет"))
        self.time_label.setText(_translate("input_widget", "Время выполнения"))
        self.time.setToolTip(_translate("input_widget", "Время выполнения"))
        self.time.setDisplayFormat(_translate("input_widget", "HH:mm"))
        self.add_button.setToolTip(_translate("input_widget", "Добавить в список"))
        self.add_button.setText(_translate("input_widget", "Добавить"))
