# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 242)
        MainWindow.setMinimumSize(QtCore.QSize(700, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.table_area = QtWidgets.QScrollArea(self.centralwidget)
        self.table_area.setWidgetResizable(True)
        self.table_area.setObjectName("table_area")
        self.table_contents = TableContents()
        self.table_contents.setGeometry(QtCore.QRect(0, 0, 712, 155))
        self.table_contents.setObjectName("table_contents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.table_contents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.table_contents)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.table_area.setWidget(self.table_contents)
        self.gridLayout.addWidget(self.table_area, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 1)
        self.head = Head(self.centralwidget)
        self.head.setObjectName("head")
        self.gridLayout.addWidget(self.head, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 732, 20))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_Qt = QtWidgets.QAction(MainWindow)
        self.action_Qt.setObjectName("action_Qt")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_6)
        self.menu_3.addAction(self.action_7)
        self.menu_4.addAction(self.action_Qt)
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TimeManager"))
        self.menu.setTitle(_translate("MainWindow", "&Нейронная сеть"))
        self.menu_2.setTitle(_translate("MainWindow", "&Файл"))
        self.menu_3.setTitle(_translate("MainWindow", "&Очередь"))
        self.menu_4.setTitle(_translate("MainWindow", "&Справка"))
        self.action.setText(_translate("MainWindow", "&Обучить"))
        self.action_2.setText(_translate("MainWindow", "О&чистить"))
        self.action_3.setText(_translate("MainWindow", "Сохранить"))
        self.action_4.setText(_translate("MainWindow", "Выход"))
        self.action_6.setText(_translate("MainWindow", "&Выход"))
        self.action_7.setText(_translate("MainWindow", "&Очистить"))
        self.action_Qt.setText(_translate("MainWindow", "&О Qt"))

from head import Head
from tablecontents import TableContents
